version: '3'
services:
  web:
    build: .
    command: gunicorn mystical_creatures_api.wsgi:application --bind 0.0.0.0:8000
    # removed this similar to JB's code - VR
    # volumes:
    #   - .:/code
    ports:
      - "8000:8000"